### ISSUE TITLE
Basic Lexer Implementation

### ISSUE THREAD

**Issue by johneliud** [johneliud/Kisumu-Programming-Language#1]
Implement a lexer for the Kisumu Programming Language that can tokenize basic syntax elements like keywords, identifiers, operators, and delimiters.

Tasks:
1. Define tokens for basic syntax elements.
2. Implement a lexer that can scan a .ksm file and produce a list of tokens.
3. Write tests to validate tokenization.

**Comment by nyagooh** [comment]
on it
